version: "3.5"

services:

  keycloak:
    image: keycloak:3.4.4.Snapshot
    build:
      context: .
    container_name: keycloak-server
    command: ["-b", "0.0.0.0","-bmanagement","0.0.0.0","-Dkeycloak.import=/opt/jboss/keycloak/realms/person.json"]
    environment:
      JBOSS_USER: jboss
      JBOSS_PASSWORD: jboss00#
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      SI_CONNECTION_URL: http://person-service:3000/api
    volumes:
      - ./realms/person.json:/opt/jboss/keycloak/realms/person.json
      - ./:/opt/jboss/workspace
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - person-service
      - postgres

    networks:
      - backend-nw
      - database-nw

  person-service:
    image: local/person-service:1.0.0
    build:
      context: ./person-service/.
    container_name: person-service
    ports:
      - "3000:3000"
    networks:
      - backend-nw

  postgres:
    image: postgres:9.4.5
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    volumes:
      - keycloack-db:/var/lib/postgresql/data
    networks:
      database-nw:
        aliases:
          - postgres
    
networks: 
  database-nw:
  backend-nw:

volumes:
  keycloack-db:
