version: "3.5"

services:

  keycloak:
    image: wallaceroque/keycloak-ha-postgres:3.4.4.Final
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      POSTGRES_ADDR: postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      SI_CONNECTION_URL: http://person-service:3000/api
    ports:
      - "8080:8080"
    depends_on:
      - person-service
      - postgres

    networks:
      - backend-nw
      - database-nw

  person-service:
    image: wallaceroque/person-service:0.0.1
    container_name: person-service
    ports:
      - "3000:3000"
    networks:
      - backend-nw

  postgres:
    image: postgres:9.4.5
    container_name: keycloak-db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: postgres
    volumes:
      - keycloack-db:/var/lib/postgresql/data
    networks:
      database-nw:
        aliases:
          - postgres
    
networks: 
  database-nw:
  backend-nw:

volumes:
  keycloack-db:
